import { readFileSync } from "node:fs";
import { escapeCurrencyDollars, normalizeMathDelimiters } from "@assistant-ui/react-markdown";
const raw = readFileSync("/w/answer.txt", "utf8");
const out = normalizeMathDelimiters(escapeCurrencyDollars(raw));
const tail = out.slice(out.indexOf("Alternatively"));
console.log("--- normalised tail ---");
console.log(JSON.stringify(tail));
console.log("\n--- does the array block become $$? ---");
console.log("contains '$$\\n\\begin{array}':", tail.includes("$$\n\\begin{array}"));
console.log("count of $$ in tail:", (tail.match(/\$\$/g) || []).length);
console.log("still has \\[ :", tail.includes("\\["));
