"""message reasoning

A model's own thinking, kept in its own column rather than marked up inside
`content`. The two are different things to a reader, and — the reason it is a
column — reasoning is never sent back to the model as history, so a scheme that
had to parse it out of the prose would send it back the first time the parsing
was wrong.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-28 15:00:13.871871+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401  (autogenerate emits it inside JSONB)
from sqlalchemy.dialects import postgresql  # noqa: F401  (JSON().with_variant)

# The two imports above are unused in most migrations and are here anyway.
# Autogenerate renders a `JSON().with_variant(JSONB(), "postgresql")` column as
# `sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql")`
# and imports neither name, so the migration fails at runtime with a NameError
# rather than at generation time — in the container, on a fresh database, after
# a clean build.

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reasoning", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("reasoning")

    # ### end Alembic commands ###
