"""calendar period quotas, api_key scope, quota resets

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-15 09:21:14.100956+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Note: LimitScope gains `api_key` in this release and needs no DDL. The enum
    # columns are plain VARCHARs — SQLAlchemy's Enum(native_enum=False) does not
    # create a CHECK unless asked — so adding a value is a code change only. See
    # ADR 0005.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quota_resets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rule_id"], ["limit_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quota_resets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quota_resets_rule_effective", ["rule_id", "effective_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quota_resets_rule_id"), ["rule_id"], unique=False)

    with op.batch_alter_table("limit_rules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "period",
                sa.Enum(
                    "day",
                    "week",
                    "month",
                    "quarter",
                    "year",
                    name="period_kind",
                    native_enum=False,
                    length=32,
                ),
                nullable=True,
            )
        )
        batch_op.alter_column("window_seconds", existing_type=sa.INTEGER(), nullable=True)
        # The old UNIQUE could not do its job once `period` joined it: SQL treats
        # NULLs as distinct, so two identical rolling rules (period NULL) would both
        # be accepted. The same flaw already applied to global rules, whose scope_id
        # is NULL. Replaced by a unique *expression* index that COALESCEs the
        # nullable parts to sentinels no real value can take.
        batch_op.drop_constraint(batch_op.f("uq_limit_rules_scope_metric_window"), type_="unique")
        batch_op.create_check_constraint(
            "ck_limit_rules_one_window_kind",
            "(window_seconds IS NOT NULL AND period IS NULL) OR (window_seconds IS NULL AND period IS NOT NULL)",
        )

    # Raw DDL rather than op.create_index: passing sa.text() expressions to
    # create_index silently emits nothing (verified — the index was simply absent
    # afterwards), whereas the SQL itself is valid on both PostgreSQL and SQLite.
    op.execute(
        "CREATE UNIQUE INDEX uq_limit_rules_identity ON limit_rules ("
        "scope, "
        "coalesce(scope_id, '00000000-0000-0000-0000-000000000000'), "
        "metric, "
        "coalesce(window_seconds, -1), "
        "coalesce(period, ''))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # IF EXISTS so a downgrade is idempotent and survives a database left partway
    # through by an interrupted run. Supported by both PostgreSQL and SQLite.
    op.execute("DROP INDEX IF EXISTS uq_limit_rules_identity")
    # Everything else in one batch block. SQLite cannot ALTER a table to add a
    # constraint at all, so restoring the old UNIQUE has to happen inside the
    # copy-and-move rebuild rather than as a standalone op.
    with op.batch_alter_table("limit_rules", schema=None) as batch_op:
        batch_op.drop_constraint("ck_limit_rules_one_window_kind", type_="check")
        batch_op.alter_column("window_seconds", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("period")
        batch_op.create_unique_constraint(
            "uq_limit_rules_scope_metric_window",
            ["scope", "scope_id", "metric", "window_seconds"],
        )

    with op.batch_alter_table("quota_resets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quota_resets_rule_id"))
        batch_op.drop_index("ix_quota_resets_rule_effective")

    op.drop_table("quota_resets")
    # ### end Alembic commands ###
